### PR TITLE
Remove rule that is not used

### PR DESCRIPTION
**Pull request by jcavar**
From my experience so far, it seems that we don't really use tabs.

### CODE REVIEW

**Comment by Dundo7** [comment]
Hej, mislim da bismo trebali ostaviti jer sigurno u ostalim projektima koristimo. Mozda si naletio na neki stari projekt gdje je bilo zbrda zdola napravljeno i svatko je gurao svoje.
Dodao sam LE da oni daju svoj komentar pa ako se slazu s tvojom konstatacijom promijenimo to bez problema.

**Comment by goranbrl** [comment]
I agree with @Dundo7 here. Xcode automatically formats tabs to 4 spaces, however this note here is to enforce that people don't put those spaces by themselves by mashing the space button 😄

**Comment by jcavar** [comment]
Ok, maybe I misunderstood what this meant.

When talking about tabs vs spaces, I think tab usually refers to the special character. This character can be configured to show `X` number of spaces, but it is still one character.

In Xcode (and other editors), Tab key can be configured to insert `X` spaces:

tab-space

https://ostrowski.ninja/use-tabs-not-spaces/
https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e


Was the idea of this rule to say that Tab key should be mapped to insert 4 spaces?

**Comment by hhrvoic** [comment]
To chime in, I guess it's a matter of terminology here, and I agree with Josip, this rule is a bit misleading. If we want to use spaces (for example 4 spaces) instead of one tab character (I saw this on most of on our projects). Cause it would make someone think that he should change spaces settings in xcode to tabs.

I think it's common sense for people to not smash the space button x times :D 
https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Review by hhrvoic — APPROVED** [review]

**Pull request merged**
